version: "3.8"
services:
  dockge:
    image: louislam/dockge:latest
    restart: unless-stopped
    ports:
      # Host Port:Container Port
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - $HOME/docker-compose-data/dockge:$HOME/docker-compose-data/dockge
    environment:
      # Tell Dockge where is your stacks directory
      - DOCKGE_STACKS_DIR=$HOME/docker-compose-data/dockge